version: '2'
services:
  zookeeper:
    image: docker.io/confluentinc/cp-zookeeper:latest
    networks:
      - kafka-example
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: docker.io/confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    networks:
      - kafka-example
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: docker.io/provectuslabs/kafka-ui
    networks:
      - kafka-example
    ports:
      - 9080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    # volumes:
    #   - ~/kui/config.yml:/etc/kafkaui/dynamic_config.yaml

networks:
  kafka-example:
